#Sales.Api Build Pipeline
 
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - src/api/AdventureWorks.Sales.Api/**
      - src/services/sales/AdventureWorks.Sales/**
      - test/services/sales/AdventureWorks.Sales/**

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- checkout: self
  displayName: 'Checkout'

- task: UseDotNet@2
  inputs:
    packageType: sdk
    version: '8.x'

- task: DotNetCoreCLI@2
  displayName: Restore Nuget Packages
  inputs:
    command: 'restore'
    projects: 'src/services/sales/*.csproj'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: 'Build Sales Service'
  inputs:
    command: 'build'
    projects: 'src/api/sales/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Run Unit Test'
  inputs:
    command: 'test'
    projects: 'test/services/sales/*.csproj'
    arguments: '--configuration $(buildConfiguration)'