#Sales.Api Build Pipeline
 
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - src/api/sales/AdventureWorks.Sales.Api/**
      - src/common/AdventureWorks.Common/**
      - src/common/AdventureWorks.Messaging/**
      - src/common/AdventureWorks.Contracts/**
      - src/common/AdventureWorks.Events/**
      - src/common/AdventureWorks.Middlewares/**
      - src/services/sales/AdventureWorks.Sales.Customers/**
      - src/services/sales/AdventureWorks.Sales.Domain/**
      - src/services/sales/AdventureWorks.Sales.Infrastructure/**
      - test/api/sales/AdventureWorks.Sales.Api.Test/**
      - test/common/AdventureWorks.Common.Test/**
      - test/common/AdventureWorks.Messaging.Test/**
      - test/common/AdventureWorks.Contracts.Test/**
      - test/common/AdventureWorks.Events.Test/**
      - test/common/AdventureWorks.Middlewares.Test/**

pr:
  branches:
    include:
      - main

variables:
  - group: SalesApiVariableGroup
  - name: my-passed-variables
    value: $[variables.minor]

stages:
- stage: Build
  displayName: Build and Test
  
  jobs:
  - job: Build
    displayName: Build Job
    
    pool:
      vmImage: 'windows-latest'
    
    steps:

      - task: PowerShell@2
        displayName: 'Log version variables'
        inputs:
          targetType: 'inline'
          script: |
            Write-Host "Minor version: $(env:major).$(env.minor).$(env.patch)"