version: '3.4'

services:
  adventureworks.gateway.api:
    image: adventureworksgatewayapi:dev
    container_name: AdventureWorks.Gateway.API
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "AdventureWorks.Gateway.API"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=
    volumes:
      - D:\Projects\AdventureWorks\AdventureWorks.Gateway.API:/app
      - D:\Projects\AdventureWorks:/src
      - C:\Users\Junaid Sultan\vsdbg\vs2017u5:/remote_debugger:rw
      - C:\Users\Junaid Sultan\.nuget\packages\:/root/.nuget/packages:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /root/.nuget/packages  \"/app/bin/Debug/net6.0/AdventureWorks.Gateway.API.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
  adventureworks.sales.api:
    image: adventureworkssalesapi:dev
    container_name: AdventureWorks.Sales.API
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "AdventureWorks.Sales.API"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=
    volumes:
      - D:\Projects\AdventureWorks\AdventureWorks.Sales.API:/app
      - D:\Projects\AdventureWorks:/src
      - C:\Users\Junaid Sultan\vsdbg\vs2017u5:/remote_debugger:rw
      - C:\Users\Junaid Sultan\.nuget\packages\:/root/.nuget/packages:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /root/.nuget/packages  \"/app/bin/Debug/net6.0/AdventureWorks.Sales.API.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
