version: '3.9'

services:
  adventureworks.gateway.api:
    image: adventureworksgatewayapi:dev
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "AdventureWorks.Gateway.API"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=
    volumes:
      - D:\AdventureWorks\AdventureWorks.Gateway.API:/app
      - D:\AdventureWorks:/src
      - C:\Users\junaid.sultan\vsdbg\vs2017u5:/remote_debugger:rw
      - C:\Users\junaid.sultan\.nuget\packages\:/root/.nuget/packages:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /root/.nuget/packages  \"/src/../Visual Studio Projects/GitHub/Microservices/AdventureWorks/AdventureWorks.Gateway.API/bin/Debug/net6.0/AdventureWorks.Gateway.API.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
  adventureworks.sales.api:
    image: adventureworkssalesapi:dev
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "AdventureWorks.Sales.API"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=
    volumes:
      - D:\AdventureWorks\AdventureWorks.Sales.API:/app
      - D:\AdventureWorks:/src
      - C:\Users\junaid.sultan\vsdbg\vs2017u5:/remote_debugger:rw
      - C:\Users\junaid.sultan\.nuget\packages\:/root/.nuget/packages:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /root/.nuget/packages  \"/src/../Visual Studio Projects/GitHub/Microservices/AdventureWorks/AdventureWorks.Sales.API/bin/Debug/net6.0/AdventureWorks.Sales.API.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
