# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build .NET

on:
  push:
    branches: [ "main" ]
    
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        
    - name: Restore NuGet packages
      run: |
        find ./src -name '*.csproj' -exec dotnet restore {} \;

    - name: Display restored packages
      run: |
        find ./src -name 'obj' -type d -prune -exec ls -l {} \;
      
    - name: Build projects
      run: |
        find ./src -name '*.csproj' -exec dotnet build {} --no-restore \;

    - name: Display build output
      run: |
        find ./src -name 'bin' -type d -prune -exec ls -l {} \;
